### ISSUE TITLE
bladeRF 2.0 micro xA4

### ISSUE THREAD

**Issue by sp8c3** [Nuand/bladeRF-wiphy#1]
Does it also work on the smaller bladeRF, the bladeRF 2.0 micro xA4?

**Comment by j-forristal** [comment]
Listed in docs, under Status section:
https://www.nuand.com/bladeRF-wiphy/

"The bladeRF 2.0 micro xA4’s FPGA is too small to fit all parts of the DSSS RX, and OFDM RX and TX modems. "
