### ISSUE TITLE
wave.do is missing

### ISSUE THREAD

**Issue by MyTechCatalog** [Nuand/bladeRF-wiphy#3]
I was following along the instructions on how to Simulate bladeRF-wiphy in Modelsim on this page: https://www.nuand.com/bladeRF-wiphy-simulation but could not find wave.do anywhere.

**Comment by rghilduta** [comment]
Thanks for pointing this out! Please refresh the page, the links have been updated. The link for wave.do is https://nuand.com/downloads/wave.do and the gzipped CSV is at https://nuand.com/downloads/rx-0.csv.gz .

**Comment by MyTechCatalog** [comment]
Thanks!
