### ISSUE TITLE
Reference CSV file (rx-0.csv) is missing.

### ISSUE THREAD

**Issue by MyTechCatalog** [Nuand/bladeRF-wiphy#4]
When I try to access https://nuand.com/downloads/rx-0.csv, I get:
Not Found
The requested URL was not found on this server.

**Comment by rghilduta** [comment]
Fixed! Also, the compressed gzip of CSV is available at https://nuand.com/downloads/rx-0.csv.gz . Also, see #3 .

**Comment by MyTechCatalog** [comment]
Thanks!
