### ISSUE TITLE
[question] Is ad-hoc supported?

### ISSUE THREAD

**Issue by alphafox02** [Nuand/bladeRF-wiphy#6]
Does bladerf-wiphy support ad-hoc mode? It appeared so, but I don’t seem to get any activity with it all running. Just curious to know if it’s even something that should work before I dig deeper.

**Comment by rghilduta** [comment]
While I have not tested ad-hoc mode, I think ad-hoc mode is functionality that is mostly differentiated at the MAC level in mac80211. The underlying PHY (bladeRF-wiphy) shouldn't have to behave differently between ad-hoc and AP/STA mode. Curious to hear how your experiments pan out!

**Comment by alphafox02** [comment]
I’ve tried ad-hoc/ibss and it does seem to allow for such configurations and I can see the ssid being broadcasted. I’ve tried to connect the bladerf and a Pi4 over adhoc and I am able to get them to merge to the same cell. I have also been able to assign an IP to their respective interfaces and ping back and forth. I think this proves it works. Now I just need to learn more about mesh.
